

export const COUNTRIES = [
  { value: 'all', label: 'All Countries' },
  { value: 'au', label: 'Australia' },
  { value: 'bd', label: 'Bangladesh' },
  { value: 'ca', label: 'Canada' },
  { value: 'in', label: 'India' },
  { value: 'id', label: 'Indonesia' },
  { value: 'my', label: 'Malaysia' },
  { value: 'pk', label: 'Pakistan' },
  { value: 'ph', label: 'Philippines' },
  { value: 'sg', label: 'Singapore' },
  { value: 'ae', label: 'UAE' },
  { value: 'gb', label: 'United Kingdom' },
  { value: 'us', label: 'United States' },
  { value: 'other', label: 'Other' },
];

export const CATEGORIES = [
  { value: 'all', label: 'All Categories' },
  { value: 'adult-18-plus', label: 'Adult/18+' },
  { value: 'art-design', label: 'Art & Design' },
  { value: 'business', label: 'Business' },
  { value: 'community', label: 'Community' },
  { value: 'dramas-series', label: 'Dramas & Series' },
  { value: 'education', label: 'Education' },
  { value: 'food-cooking', label: 'Food & Cooking' },
  { value: 'gaming', label: 'Gaming' },
  { value: 'health-fitness', label: 'Health & Fitness' },
  { value: 'jobs-career', label: 'Jobs & Career' },
  { value: 'lifestyle', label: 'Lifestyle' },
  { value: 'movies-tv-shows', label: 'Movies & TV Shows' },
  { value: 'music-audio', label: 'Music & Audio' },
  { value: 'news-media', label: 'News & Media' },
  { value: 'politics', label: 'Politics' },
  { value: 'science', label: 'Science' },
  { value: 'sports', label: 'Sports' },
  { value: 'technology', label: 'Technology' },
  { value: 'travel-tourism', label: 'Travel & Tourism' },
  { value: 'other', label: 'Other' },
];
